### ISSUE TITLE
would this add to bower?

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.vimeo_player#1]
would this add to bower? thanks!

**Comment by pupunzi** [comment]
You should find it on bower now.

**Comment by weilinzung** [comment]
I try to search on bower.io, but nothing over there. or run `bower install jQuery.mb.vimeo_player --save` not fund.

**Comment by pupunzi** [comment]
Just tested successfully:   `bower install jquery.mb.vimeo_player`

Don't know why it's not listed on bower.io

**Comment by weilinzung** [comment]
ok. now it is working, but the repo has no `dist` folder and `bower.json`. Would this cause any issues? 

when I run `gulp watch or gulp production` it seems not combine this Vimeo scrips to my main JS.
`Uncaught TypeError: $(...).vimeoPlayer is not a function
    at HTMLDocument.<anonymous> (main.js:90)
    at f (jquery.js:3583)
    at p (jquery.js:3651)`

I did the same way to install this Vimeo script like Youtube one, but the youtube one is running fine.

thanks!

**Comment by weilinzung** [comment]
I figure out why always said Uncaught TypeError.

The Repo one and the Demo one has different config name which are `jQuery.vimeoPlayer`(demo & doc )  and `jQuery.vimeo_player`(repo). 

Please fix.
