### ISSUE TITLE
Video flickers when window is resized

### ISSUE THREAD

**Issue by tleifj** [pupunzi/jquery.mb.vimeo_player#13]
If you resize the browser window while the video is playing, it flickers. This is happening on all major browsers, Mac and Windows.

**Comment by pupunzi** [comment]
Hi,
that is due to an issue of the Vimeo API with the resize behavior that tries to fit the video on the visible view forcing some hacks for calculating the correct size once the view is resized. 
On the next release the flickering will be less invasive but can not removed.
