### ISSUE TITLE
Video is not full screen on Google Chrome

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.vimeo_player#17]
LINK: 

Google Chrome: Version 66.0.3359.181 (Official Build) (64-bit)
macOS

The top part of the screen has white spacing.

thanks!

**Comment by pupunzi** [comment]
I presume is something on your CSS definition that is causing your issue.

**Comment by weilinzung** [comment]
do you think this inline CSS that created from this JS?

```
position: absolute;
z-index: 0;
overflow: hidden;
left: 0px;
top: 0px;
opacity: 1;
width: 1783px;
height: 1002.8px;
margin-top: 0px;
margin-left: -141.1px;
max-width: initial;
```

Try width: 100% !important and height: 100%  !important would create more spaces~

**Comment by weilinzung** [comment]
Hi, I think it is because of the `mb.vimeo.player` would not support this type of video ratio: 
`1.90:1`
`2048x1080`

I try to use your DEMO example HTML and change to the video that I have which produce the same issue on Chrome. screenshot(dark gray part): http://oi68.tinypic.com/6gedea.jpg

Any improvements if you could do on the script?

thanks!

**Comment by pupunzi** [comment]
Yes, it's a problem of aspect-ratio; add the "ratio" parameter and set it to 1.90 and it works.

**Comment by weilinzung** [comment]
Is gonna on the updates of `mb.vimeo.player` or I have to manually add to my config js?

if it is in the updates, would it possibly be automated detect the video ratio or from the Vimeo settings? Because for the client may have different ratio videos each time and doesn't know to code, they may don't know how and what to do with it. 

 THANKS!

**Comment by pupunzi** [comment]
Hi,
this is one of the options you already can set for the player. Just add it when you initialize the player.

It doesn't seam you are using my Wordpress plug-in where you can set the aspect ratio from the settings page... If you implemented it on your own the only way is to add manually the aspect ratio value where you initialize the player. There's no way to auto-detect it as Vimeo doesn't return this information.

All the best,
Matteo
