### ISSUE TITLE
Abundance and videos being cropped. 

### ISSUE THREAD

**Issue by mattnelsonuk** [pupunzi/jquery.mb.vimeo_player#19]
The following line is causing me issues

```
var abundance = vimeo_player.isPlayer ? 0 : el.outerHeight() * .15;
```

It is adding the padding every time which is making it crop the outside edge of my videos. Is there a reason for this as for me, the video fits perfectly when it's up tot he edge. I set abundance = 0 manually in the JS for my background videos to get them to fit in properly.

Not sure if this is a bug or not? Or if there is some other way to control this?

**Comment by pupunzi** [comment]
Hi,
That is not a bug.
Is used to hide the vimeo logotype on the bottom.
I'll introduce an option for that.
