### ISSUE TITLE
 Periodically appear the proposed video

### ISSUE THREAD

**Issue by arny1488** [pupunzi/jquery.mb.vimeo_player#20]
Hello! How can I prevent the proposed video?
Autorun and repeat enabled.

A source: http://www.spindle-service.ru/about/ (Block at the bottom of the page)

![ad5caxbrptg](https://user-images.githubusercontent.com/10730754/48663893-b44a3400-eaa7-11e8-8c26-16b47094723d.jpg)

**Comment by pupunzi** [comment]
Hi,
just tested your site and I couldn't repeat your issue...
What browser are you testing with?

**Comment by arny1488** [comment]
My browser is google chrome. The fact is that the problem does not always appear. I once caught her. Another user caught several times, he sent a photo.

> Привет, 
> просто протестировал ваш сайт, и я не смог повторить вашу проблему ... С 
> каким браузером вы тестируете?
