### ISSUE TITLE
Documentation refers to showYTLogo property

### ISSUE THREAD

**Issue by adam-jones-net** [pupunzi/jquery.mb.vimeo_player#29]
This seems to be something left over from your YouTube player documentation.  Can I request that you update your documentation for this project ?    Also, is there an alternative property in this player?

**Comment by pupunzi** [comment]
showYTLogo  -> fixed

the available properties are:
ratio              : 16 / 9, // "16/9" or "4/3"
			videoURL           : null,
			quality            : "1080p",//4K, 2K, 1080p, 720p, 540p, 360p and 240p
			startAt            : 0,
			stopAt             : 0,
			autoPlay           : true,
			fadeTime           : 1000,
			vol                : 5, // 1 to 10
			addRaster          : false,
			opacity            : 1,
			mute               : true,
			loop               : true,
			showControls       : true,
			show_vimeo_logo    : true,
			stopMovieOnBlur    : true,
			realfullscreen     : true,
			playOnMobile       : true,
			playsinline        : true,
			mobileFallbackImage: null,
			gaTrack            : false,
			optimizeDisplay    : true,
			mask               : false,
			align              : 'center,center', // top,bottom,left,right
