### ISSUE TITLE
mobileFallbackImage is not working again

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.vimeo_player#4]
Hi,

the`mobileFallbackImage` is not working anymore since last update. This time the entire `video-bg-inner` div is gone on small devices, maybe this cause it.

[https://s16.postimg.org/i6a15wvgl/image1.png](https://s16.postimg.org/i6a15wvgl/image1.png)

thanks!

**Comment by pupunzi** [comment]
Hi,
no _video-bg-inner_ class on my script... Anyway there was a bug that could prevent the display of the fallback image. I just released the 1.0.7 version with a bug fix that should have fixed the issue.

let me know

**Comment by weilinzung** [comment]
This happen again, fallback image is not working again!!!

**Comment by pupunzi** [comment]
With the latest 1.0.9 should be fixed again. Probably a merging overwrites the previous fix.
