### ISSUE TITLE
Video Mute doesn't Work Properly

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.vimeo_player#5]
Hi,

I am use `VPStart`, but when the page is loading the video then actually has music play. The music will disappear when the video is started to play.

I initial the Js with `mute: true`, then create a `VPStart` function for hide the preloader. 

Please fix and help,

thanks!

**Comment by pupunzi** [comment]
you should provide an URL where I can check the issue

**Comment by weilinzung** [comment]
Ok. I haven't put the site live yet, so I don't have the live link yet. I try to switch another video to try, it seems no problem now. I can keep you update on this. thank you for looking into this!

**Comment by weilinzung** [comment]
here is the link: https://goo.gl/133KwPu, it has music before the video start play.
also try to use `Vol:1`, it seems also not change the volume.

**Comment by pupunzi** [comment]
with the last 1.0.8 release it should be fixed
