### ISSUE TITLE
IE not full screen

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.vimeo_player#6]
Hi,

I just did some tests on Windows with IE 10, IE11 & IE Edge, all of them have same issue which is the video wouldn't take the full browser window.  I try to change the CSS, it seems the CSS cause the issue but it still not fix the issue.

here are the screenshots: 
https://s30.postimg.org/oxxx3mfg1/screenshot1-1123.png
https://s30.postimg.org/b5ji7zooh/screenshot2-1123.png

Please help and fix,
thanks!

**Comment by weilinzung** [comment]
I check on the option `optimizeDisplay`, I set it to `true`, but seems not fix that. Please check this option if working on IE. Also Youtube has same issue.

**Comment by weilinzung** [comment]
Ok, I try my own to fix it by also adding the plugin CSS(`jquery.mb.vimeo_player.min.css`) to my build system. Right now fix the issue on IE. Thanks!

**Comment by pupunzi** [comment]
CSS is not an optional; the component needs it to work.
All the best,
Matteo
