### ISSUE TITLE
Video player keep starting

### ISSUE THREAD

**Issue by armansansd** [pupunzi/jquery.mb.vimeo_player#8]
Hi, 
I'm using your component, 
It is working great, but I have a little trouble. Sometime the video start by itself even if I disable the autostart. Do you have any clues ? Have you ever encountered this kind of trouble. 
I look at the network with the dev. tool of Firefox, and few segments are being download during the loading of the page, sometime it stops, sometime it continue and the video start playing.

**Comment by pupunzi** [comment]
@armansansd 
Hi, 
do you have an URL where I can see the issue?
Did you notice it happens with a particular browser?
What are the settings you are using?

All the best,
Matteo

**Comment by armansansd** [comment]
Hello , 
Thank you for your very quick response  ! 
Here is the website : 
http://semper.tv/
As for the setting, 
` showControls:true
optimizeDisplay: true
fadeTime:500
autoPlay:false
loop:false
vol:100
mute:false
 startAt:0
stopAt:215
opacity:1
addRaster:false`
It happend more often on chrome / chromium. Maybe it is something I did wrong 🤕 

Cheers, 
Arman

**Comment by pupunzi** [comment]
Hi,
That is something that doesn't happens on my test page on any browser. 
Did you change somehow the initial behavior?

**Comment by armansansd** [comment]
Hi, 
I started all over again, cleaned up my code, use the default javascript file and default setting. (I've been previously fiddling around too much). 
The problem occurs only on chromium and chrome, on mac and linux (archlinux). It happens irregularly, mostly when the user scrolls the page before the video is loaded. This is very strange. 
I'm sorry to be so vague, i'm a bit out of my comfort zone :) 

So is it possible to do a loading page to avoid this problem happening ? I'm using kirby and I load the video URL dynamically but even with a static url the problem appears.

Thank you so much for your time, i'm out of clues ! 

![log](https://user-images.githubusercontent.com/4079560/27446069-7ed225a4-577c-11e7-9263-d82a5ff3cc2a.png)

**Comment by pupunzi** [comment]
Hi,
did you try removing the iframe you added as fallback video?
`<iframe id="fallback" style='display:none; position:absolute; top:0; left: 0;' src='https://player.vimeo.com/video/216636348' width='100%' height='50vh' frameborder='0' webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

**Comment by armansansd** [comment]
yes it still, doing it. As I said I start all over again. on the local server, it load the video then sometime instead of pausing, it plays. It only plays the sound, and the progress bar is moving, but there is no images.

Could it be a problem with the api ? can use a callback function after `jQuery("#id").vimeo_player();` to display my page after the request to the api ?

**Comment by pupunzi** [comment]
It's hard to debug as I'm not able to reproduce the issue anyway :-)
I'm trying to figuring out why it doesn't pause in your case...

I see you made some changes to the original script... does it happens also if you use the original one?

You could try also forcing the pause of the video on the "VPReady" event as follow:
```
jQuery("#first_vid").on("VPReady", function(e){
                setTimeout(function(){
                    jQuery("#first_vid").v_pause();
                 }, 500);
           }); 
```

This is not a good solution but I've no other ideas at the moment.

**Comment by armansansd** [comment]
it did the trick !  
Thank you very much ! 
I don't need a clean solution for now. 

I tested on a fresh install, without all my (very badly done) changes and the problem is still happening. 
But we can close this issue for now so you don't have to lose your hair on that :) 

Thanks a lot !👍

**Comment by pupunzi** [comment]
Great!
Anyway I'll try to get what is that is making that issue.
All the best
